//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderProducts = new HashSet<OrderProducts>();
        }
    
        public int Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int PickUpPointId { get; set; }
        public int UserId { get; set; }
        public int GetCode { get; set; }
        public int OrderStatusId { get; set; }
    
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
        public virtual OrderStatuses OrderStatuses { get; set; }
        public virtual PickUpPoints PickUpPoints { get; set; }
        public virtual Users Users { get; set; }
    }
}
