//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    using System.Security.Policy;

    public partial class Products
    {
        public Products()
        {
            this.OrderProducts = new HashSet<OrderProducts>();
        }
    
        public int Id { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public decimal Cost { get; set; }
        public int SupplierId { get; set; }
        public int ManufacturerId { get; set; }
        public int ProductCategoryId { get; set; }
        public int Discount { get; set; }
        public int Count { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        
        public string DiscountColor => Discount > 15 ? "#483D8B" : "#FFFFFF";

        public string CategoryName => ProductCategories.Name + " | " + Name;

        public string PhotoPath => "/img/" + (Photo ?? "picture.png");

        public string DescriptionDevided
        {
            get
            {
                if (Description.Length > 100)
                {
                    var LastSpaceIndex = Description.Substring(0, 100).LastIndexOf(' ') + 1;
                    return Description.Substring(0, LastSpaceIndex) + '\n' + Description.Substring(LastSpaceIndex);
                }
                return Description;
            }
        }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
        public virtual ProductCategories ProductCategories { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
